baseURL = "https://www.spectrumefficiency.co.nz/"
buildFuture = true
copyright = "&copy;{year}, All Rights Reserved"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableEmoji = true
enableGitInfo = false
googleAnalytics = ""
hasCJKLanguage = true
paginate = 13
rssLimit = 100
summaryLength = 70
theme = "hugo-theme-zzo"
timeout = 10000
title = "Spectrum Efficiency"
[markup.goldmark.renderer]
hardWraps = true
unsafe = true
xHTML = true
[markup.highlight]
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[outputFormats.SearchIndex]
baseName = "index"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "SearchIndex"]
page = ["HTML", "SearchIndex"]
section = ["HTML", "RSS", "SearchIndex"]
taxonomy = ["HTML", "RSS", "SearchIndex"]
taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
