baseURL = "https://www.spectrumefficiency.co.nz/"
title = "Spectrum Efficiency"
theme = "hugo-theme-zzo"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = false

summaryLength = 70
buildFuture = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"] 

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

enableGitInfo = false
googleAnalytics = "UA-165840479-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  page = ["HTML", "SearchIndex"]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"


  # Theme configuration

[params.theme]

    bootstrapTheme = 'flatly' # Use empty value for default Bootstrap color scheme or one of the following values:
    # bolt, bstrap, btcn, calabaza, cerulean, cosmo, cyborg, darkly, flatly, hoff, journal,
    # kdo_flatly, kdo2, kunsch, lumen, lux, malibu, materia, minim, minty, pulse, sandstone, 
    # signa, simplex, sketchy, slate_accessibility_ready, slate, solar, sonic, spacelab, united, yeti

    backgroundColor = '' # If color is set, it will be used for background. Set empty for default.
    backgroundImage = '' # Set background image, use file name with path in static folder, e.g. 'img/background.jpg'
    backgroundImageRepeat = '' # Set background image repeat option, see https://developer.mozilla.org/de/docs/Web/CSS/background-repeat


# Header configuration

[params.theme.header]
    # The following options are mostly used when the navbar is in "header" mode, i.e. not fixed-top
    fontColor = '' # header font color, leave empty for default
    linkColor = '' # header link color, leave empty for default
    backgroundColor = '' # header background color, leave empty for default

    image = 'img/header_bg_example.jpg' # Use header image. This option is only valid if the theme is configured to the "header" style. 
    
    width = 2512 # Width of header image. Please set this value to the correct size, because it will be used for size calculation.
    height = 673 # Height of header image. Please set this value to the correct size, because it will be used for size calculation.
    altText = 'alt text for header image' # Set alt text for header image, default empty
    displayHeaderText = true # display the title and subtitle - yes or no?
    titleOnImage = true # true|false, default false. Display title and subtitle as overlay in the foreground of the image. It is only possible to set the title as image overlay if an image is available. If no image is configured, the theme will do a fallback to non-overlay, i.e. title and subtitle will be displayed above the main navigation. 
    fontColorTitle = '#073642' # For all colors, please use #rrggbb format with # and 6 characters
    fontColorSubtitle = '#333333'
    overlayAlignment = 'lt' # lt = left/top, mt = middle/top, rt = right/top, lb = left/bottom, mb = middle/bottom, rb = right/bottom
    overlayDistanceVertical = '20' # Dependent on the overlayAlignment option, this option is used to modify the vertical distance between the margin and the title/subtitle. This allows to place the title and subtitle on nearly any place related to the header image. 
    overlayDistanceHorizontal = '20' # The same as above, but for horizontal distance. 
    overlayDistanceBetween = '0' # Distance between title and subtitle 
    overlayBackgroundColor = '#000000'
    overlayTransparency = '0' # default 70%, allowed values from 0 - 100 (without % sign!). This option enables a transparent background of title and subtitle. This is useful if the "titleOnImage" option is true, so the title is placed as overlay above the image. If this option is set to 0 or an empty value, the transparency color setting will be disabled. 

# Footer configuration

# To create a footer, create a directory "sections/footer" into your project’s content directory.
# Then add some content files (.md or .html) to the footer folder AND create an index.md file with the Front Matter setting
# headless: true
# Without the "headless" setting the sidebar will not be displayed! 
# See https://gohugo.io/content-management/page-bundles/#headless-bundle 
# You can modify the style with a partial "footer_column.html", see example in "layouts/partials/".
# If you don't have content files in the footer area, the demo texts from below will be shown. If you don't want this, please delete
# the [[params.theme.footer.demoColumn]] entries or just disable the footer by setting enabled = false. 

[params.theme.footer]
    enabled = true # Show the footer part
    #numberColumns = 3 # Set number of columns available in footer of a page. Use the "footer" folder in the page structure to add content. If nothing is set, the default number is 3. Currently.i.e. since v0.2 not used, the number of columns is identical to the number of files in footer directory.
    fontColor = '#f9fcf9' # set #rgb code, leave empty for default
    linkColor = '' # Set color of links as #rrggbb code, leave empty for default
    backgroundColor = '#29281f' # Set color of background as #rrggbb code, leave empty for default

    [[params.theme.footer.demoColumn]]
    text = 'This is a placeholder for a content file of the footer. You can use Markdown or HTML here. Just place your content files into a folder "sections/footer" in your content directory, make the page bundle "headless" and enable the footer in the site config file.'

    [[params.theme.footer.demoColumn]]
    text = 'More footer content.'

    [[params.theme.footer.demoColumn]]
    text = 'To change this, please have a look at the README.md and the comments of the footer section in the config.toml file.'



# Subfooter configuration

# To create a subfooter, create a directory "sections/subfooter" into your project’s content directory.
# Then add some content files (.md or .html) to the subfooter folder AND create an index.md file with the Front Matter setting
# headless: true
# Without the "headless" setting the sidebar will not be displayed! 
# See https://gohugo.io/content-management/page-bundles/#headless-bundle 
# You can modify the style with a partial "subfooter_item.html", see example in "layouts/partials/".

[params.theme.subfooter] 
    enabled = true # Show the content below the footer
    fontColor = '' # Text color in subfooter. Leave empty to use the theme default. 
    linkColor = '' # Link color in subfooter. Leave empty to use the theme default. 
    backgroundColor = '' # Background color of subfooter. Leave empty to use the theme default. 
    demoContent = 'Powered by <a href="https://gohugo.io">Hugo</a>. Theme <a href="https://github.com/geschke/hugo-tikva">Tikva</a> by <a href="https://www.kuerbis.org">Ralf Geschke</a>. As you can see, this text is only an example of the area below the footer. To change this, please have a look at the included example site and the section "Subfooter configuration" in the config.toml file. '

# Font configuration

# In this section it is possible to modify the font settings of title, subtitle, navigation bar, body (i.e. the default text used in the content areas) and headlines h1 - h6. You can use Google Fonts as well as any font string the browser supports. 

[params.fonts]
   
    headerTitle = 'Exo' # set font, use string, e.g. "Lucida, Verdana, sans-serif". You can use any font value. Please activate Google Font option if you want to include Google Fonts, see their names on https://fonts.google.com/
    headerTitleGoogleFont = true # If the font in the above variable is a Google font, set this option to true. 
    headerTitleVariant = '800' # font variant, if available, e.g. "regular", "bold" etc. Not every font is available in multiple variants.
    headerTitleSize = '50px' # set font size, empty for default settings. Valid values are '20px', '1.2em' and so on
    
    headerSubtitle = 'Exo' # Font settings for subtitle
    headerSubtitleGoogleFont = true # If the font in the above variable is a Google font, set this option to true. 
    headerSubtitleVariant = '600' # See above
    headerSubtitleSize = '30px' # See above

    #navbar = 'Lucida, Verdana' # font settings for navigation bar
    navbarGoogleFont = false # If the font in the above variable is a Google font, set this option to true.  
    navbarVariant = '' # See above
    navbarSize = '20px' # See above

    body = '' # font settings for body content
    bodyGoogleFont = false # If the font in the above variable is a Google font, set this option to true. 
    bodyVariant = '' # See above
    bodySize = '' # See above

    headline = 'Open Sans' # font settings for body content
    headlineGoogleFont = true # If the font in the above variable is a Google font, set this option to true. 
    headlineVariant = '' # See above
    headlineBaseSize = '' # Set base font of headlines. The real size of H1 - H6 will be calculated based on this size with the same resize factors as in the CSS framework. Choose a size of 0 (zero) to use the default font size of the theme. Please use only integer values without "px", "em" or something else. 


